services:
  - type: pserv
    name: atcoder-problems-db
    env: postgres
    plan: free
    ipAllowList: []

  - type: web
    name: atcoder-problems-backend
    env: docker
    rootDir: atcoder-problems-backend
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthcheck
    envVars:
      - key: SQL_URL
        fromDatabase:
          name: atcoder-problems-db
          property: connectionString
      - key: RUST_LOG
        value: info
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: FRONTEND_REDIRECT_URL
        sync: false
      - key: CORS_ALLOW_ORIGINS
        sync: false
